# Generated by Django 4.2 on 2026-02-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_score', models.FloatField(default=0)),
                ('security_score', models.FloatField(default=0)),
                ('breach_score', models.FloatField(default=0)),
                ('children_score', models.FloatField(default=0)),
                ('sdf_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('penalty_exposure', models.FloatField(default=0)),
                ('risk_level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
        ),
    ]
